### ISSUE TITLE
xml Design error

### ISSUE THREAD

**Issue by jash-debug** [wamaithaNyamu/Group3Webapp#8]
missing xml components that need to be updated
java.lang.NullPointerException
        at android.graphics.fonts.Font_Builder_Delegate.createBuffer(Font_Builder_Delegate.java:52)
        at android.graphics.fonts.Font$Builder.createBuffer(Font.java:220)
        at android.graphics.fonts.Font$Builder.<init>(Font.java:172)

**Comment by austinmula** [comment]
Check out this url for possible solutions 
[https://stackoverflow.com/questions/57144891/how-to-fix-java-lang-illegalargumentexception-font-has-already-been-added-er]
